"""added many to many relationship btw tag and post tables

Revision ID: 25eec6ddde13
Revises: 58eaa7ba9fe3
Create Date: 2022-09-02 08:40:18.618454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25eec6ddde13"
down_revision = "58eaa7ba9fe3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_tag",
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
